# Generated by Django 4.0.5 on 2022-07-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
