# Generated by Django 4.0.5 on 2022-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('speciality', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=50)),
            ],
        ),
    ]
