# Generated by Django 4.0.5 on 2022-07-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
