# Generated by Django 4.0.5 on 2022-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_services_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='service',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='service',
            name='discription',
            field=models.CharField(max_length=300),
        ),
    ]
