# Generated by Django 4.0.5 on 2022-07-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_service_degree_remove_service_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='discription',
        ),
    ]
