# Generated by Django 4.0.5 on 2022-07-07 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_service_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dutt',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
